- name: play level variables
   hosts: local
   connection: local
   vars_file:
   - Course.yaml
   tasks:
   - name: print course inforamtion
     ansible.builtin.debug:
       msg: "Courname:{{ COURSE }} duration:{{ DURATION }} trainername: {{ TRAINER }}"