- name: inventory level variables
  hosts: local
  connection: local
  tasks:
  - name: print course inforamtion
    ansible.builtin.debug:
       msg: "Courname:{{ COURSE }} duration:{{ DURATION }} trainername: {{ TRAINER }}"