- name: ansible datatypes
  hosts: local
  connection: local
  vars:
     COURSE: "aws with Devops"  #string
     DURATION: 120  # number
     IS_LIVE: true  #boolean
     TOOLS:  #list
     - linux
     - shell
     - ansible
     CONCETPS: # map or dictionary or object. referred like {} concept is variable, CI is key and jenkins is value Scripting is key
      CI: Jenkins
      SCRIPTING: "Shell, Ansible, Terraform, Python"
  tasks:
  - name: print course inforamtion
    ansible.builtin.debug:
        msg: "Courname:{{ COURSE }} duration:{{ DURATION }} is live?: {{ IS_LIVE }}  tools are {{ TOOLS}} conepts are: {{ CONCETPS}}"