- name: loops with print names
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible-builtin.debug:
       msg: "Name: {{ item }}"   #item is reserv word for ansible programming
    loop:
    - suresh
    - raju
    - ramesh
    - Ravli
    - rama