- name: Install packages with loop
  hosts: frontend
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.package:
      name: "{{ item }}"
    loop:
    - mysql
    - nginx
    - zip
