- name: Install packages with loop
  hosts: frontend
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "mysql", state: "present" }
    - { name: "nginx", state: "absent" }
    - { name: "zip", state: "absent" }